### ISSUE TITLE
Button press hint when stimilus appears

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/n-back-child#14]
Is it better to add an instruction image below stimlus to show the button mapping to the user.

**Comment by psychelzh** [comment]
So it seems to be better indeed to show the key-meaning mapping, for the mapping is arbitrary. But this is rarely implemented in other studies. BTW, if the mapping be shown, would the counterbalance of mapping be unnecessary.

**Comment by Zhouyu0206** [comment]
How about we leave this question to this evening‘s discussion, we can ask Gui's suggestions.

**Comment by psychelzh** [comment]
From Xue, "We'd better not add this."
