### ISSUE TITLE
How to store the response when two keys are pressed simultaneously?

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/n-back-child#15]
It is better to set these trials the same as trials with no response.

**Comment by Zhouyu0206** [comment]
Agree！ The criteria to keep one of the two responses is too hard because we cannot figure out what the subject was thinking when he/she pressed two keys, so the best and simplest way is to set this kind of trials with two response as false/no response.

**Comment by psychelzh** [comment]
Okay. I will implement it then.

**Comment by psychelzh** [comment]
I wil store the reponse as `"both"`, and set the accuracy as 0 (i.e., incorrect).

**Comment by psychelzh** [comment]
Solved together with #20.

**Comment by psychelzh** [comment]
Fixed now.
