### ISSUE TITLE
Is it better to change zero-back test to be simpler?

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/n-back-child#16]
For example, to judge whether the stimulus is 5.

**Comment by Zhouyu0206** [comment]
I think this idea is also very great because it can reduce the task's difficulty for children and as you said much other research also do this, so why not?

**Comment by psychelzh** [comment]
Yes. For example, see [Zhang et al. (2015)](https://www.nature.com/articles/pr2015120#methods):

> Subjects responded to a single prespecified target number (e.g., 1, 2, 0) in the 0-back condition.

and [Massat et al. (2012)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0049392#s4):

> In the vigilant/control 0-back (N0) condition, subjects had merely to press a button with the right hand whenever the number “2” was displayed.

But see [Chen et al. (2016)](https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01804/full#h3), it used a simpler version of odd/even number judgment.

> Each 0-back condition included 11 phases in random order. The first phase was an experimental content cue: single or double; when the numeral 1 or 3 appeared, pressing button A; when the numeral 2 or 4 appeared, pressing button B. These four numbers were displayed randomly at equal probability.

**Comment by Zhouyu0206** [comment]
You mean when the number is 0, subjects give the 'yes' response; while the number isn't 0, subjects give the 'no' response?

**Comment by psychelzh** [comment]
Yes. Is it okay?

**Comment by Zhouyu0206** [comment]
Yeah~I think it's OK!

**Comment by psychelzh** [comment]
OK, I will implement this.

**Comment by psychelzh** [comment]
Drop numbers of 0 and 5, and use the same 0-back test.

**Comment by psychelzh** [comment]
@Zhouyu0206 Modifications of instruction images are necessary now.

**Comment by psychelzh** [comment]
Fixed now.
