### ISSUE TITLE
Is it necessary to counterbalance reponse mapping between subjects?

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/n-back-child#17]
For example, `target`-`Left` and `distractor`-`Right` for subjects with odd number, and `target`-`Right` and `distractor`-`Left` for subjects with even number.

**Comment by Zhouyu0206** [comment]
I think this operation is necessary because different people have a different preference for the meaning that their hands represent, so let's do this counterbalance if it's not so much trouble to you.

**Comment by psychelzh** [comment]
That makes sense. I will implement in the next release.
